server:
  port: 8080
spring:
  config:
    import:
     - "application_prod.yml"
     - "application_qa.yml"
    

  profiles:
    active:
    
     - "qa"
     - "prod"
  datasource:
    url: jdbc:h2:mem:accountsdb
    driverClassName: org.h2.Driver
    username: admin
    password: 1234
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


    
build:
  version: "1.0" 
  
accounts:
  message: "Welcome to ZettaBank accounts related APIs"
  contactDetails:
    name: "Sunil Joseph - Developer"
    email: "sunil@zettabank.com"
  onCallSupport:
    - (40) 123-45678
    - (40) 456-13459
     